language: node_js
node_js:
- '8'
deploy:
  provider: npm
  email: brenton.house@gmail.com
  api_key:
    secure: 
  on:
    tags: true
    repo: mobilerhero/mobile-bluebird
  branches:
    only:
    - master
